mod_loader=sponge

included_projects=:api, :common

enable_hangar_upload=false
enable_curseforge_upload=false
enable_mod_update=false

upload_release_type=alpha
upload_recommended=true

viaversion_version=5.0.0-SNAPSHOT

modrinth_upload_supported_loaders=sponge

hangar_upload_dependencies=ViaVersion, ViaBackwards
hangar_upload_minecraft_versions=1.21.4
